open_for_seconds:
  name: Öffne für Sekunden
  description: Öffnet ein Ventil für eine bestimmte Zeitdauer.
  fields:
    valve:
      name: Ventil
      description: Wähle ein Ventil aus deiner Installation
      required: true
      selector:
        entity:
          domain: valve
          integration: plantbot
    duration:
      name: Zeit
      description: Wie lange soll gegossen werden?    
      required: true
      example: 10
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: Sekunden

open_for_volume:
  name: Öffne für Volumen
  description: Öffnet ein Ventil, bis eine bestimmte Menge Wasser geflossen ist.
  fields:
    valve:
      name: Ventil
      description: Wähle ein Ventil aus deiner Installation
      required: true
      selector:
        entity:
          domain: valve
          integration: plantbot
    volume:
      name: Volumen
      description: Welches Volumen soll gegossen werden?
      required: true
      example: 5
      selector:
        number:
          min: 1
          step: 5000
          unit_of_measurement: ml
