name: Fix manifest & update release on publish
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  fix_manifest_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version from release tag
        id: ver
        run: |
          tag="${{ github.event.release.tag_name }}"
          ver="${tag#v}"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "ver=$ver" >> $GITHUB_OUTPUT
      - name: Read current manifest version
        id: manifest
        run: |
          cur=$(jq -r '.version' custom_components/taubenschiesser/manifest.json)
          echo "cur=$cur" >> $GITHUB_OUTPUT
      - name: Update manifest.json if needed
        if: steps.manifest.outputs.cur != steps.ver.outputs.ver
        run: |
          jq --arg v "${{ steps.ver.outputs.ver }}" '.version = $v' \
            custom_components/taubenschiesser/manifest.json > custom_components/taubenschiesser/manifest_tmp.json
          mv custom_components/taubenschiesser/manifest_tmp.json custom_components/taubenschiesser/manifest.json
      - name: Commit change (if any) and move tag to new commit
        if: steps.manifest.outputs.cur != steps.ver.outputs.ver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.ver.outputs.tag }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name  "github-actions[bot]"
          git add -f custom_components/taubenschiesser/manifest.json
          git commit -m "chore: bump manifest to ${{ steps.ver.outputs.ver }}" || true
          git tag -f "$TAG"
          git push origin ":refs/tags/$TAG"
          git push origin "$TAG"
          git push origin HEAD:main
      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.ver.outputs.tag }}
          name: ${{ steps.ver.outputs.tag }}
          generate_release_notes: true
          draft: false
          prerelease: false
